#!/bin/bash
#	PRG="$(basename "$0")"
#	PRGDIR="$(readlink -f "$(dirname "$0")")"
source entities
	strict.set on

	source "./$PRG.bash"
	
	filename="$1"
	echo "Filename: $filename"

	text=( "$(textfiletype "$filename" 2>/dev/null)" )
	echo "textfiletype: |${text[@]}|"
	echo $text
	echo ${text[0]}
		
	editstr="editstr=$(editorsyntaxstring ${text[@]} 2>/dev/null)"
	echo $editstr