#!/bin/bash
#	PRG="$(basename "$0")"
#	PRGDIR="$(readlink -f "$(dirname "$0")")"
source entities
	strict.set on

	EDITOR=''
	source ./editor.set.bash

	source "$PRGDIR/$PRG.bash"

	echo e  ${EDITOR:-}
	echo ee ${_ent_EDITOR:-}
	echo se ${SUDO_EDITOR:-}
	echo le ${SELECTED_EDITOR:-}
	
	filename="$1"
	filetype="$2"
	echo "Filename: $filename" "Filetype: $filetype"

	text=( "$(textfiletype "$filename" 2>/dev/null)" )
	echo "textfiletype: |${text[@]}|"

	editstr="editstr=$(editorsyntaxstring ${text[@]} 2>/dev/null)"
	echo $editstr