declare   -- PRG='' PRGDIR=''
declare   -x OLDIFS=$IFS
declare  -nx OIFS="OLDIFS"
declare  -ix _ent_VERBOSE=$( [[ -t 0 ]] && echo 1 || echo 0)
declare  -ix _ent_COLOR=1
declare   -x colorreset="\x1b[0;39;49m"
declare   -x color0="\x1b[0;39;49m"
declare   -x colordebug="\x1b[35m"
declare   -x colorinfo="\x1b[32m"
declare   -x colornotice="\x1b[34m"
declare   -x colorwarning="\x1b[33m"
declare  -nx colorwarn='colorwarning'
declare   -x colorerr="\x1b[31m"
declare  -nx colorerror='colorerr'
declare   -x colorcrit="\x1b[1;31m"
declare  -nx colorcritical='colorcrit'
declare   -x coloralert="\x1b[1;33;41m"
declare   -x coloremerg="\x1b[1;4;5;33;41m"
declare  -nx colorpanic='coloremerg'
declare  -nx coloremergency='coloremerg'
declare   -p _ent_VERSION &>/dev/null || declare -r _ent_VERSION='4.20.420 beta'
declare   -x _ent_SCRIPT_VERSION='0.00 prealpha'
declare  -ix _ent_DRYRUN=0
declare  -ix _ent_DEBUG=0
declare   -x _ent_LOCKFILE=''
declare  -ax _ent_LOCKFILES=()
declare  -ix _ent_LOCKTIMEOUT=86400
declare  -ix STRICT=0
declare  -ix EXITTRAP=0
declare   -x EXITTRAPFUNCTION='{ cleanup "$?" "${LINENO:-}"; }'
declare  -ix TABWIDTH=4
declare  -ix TABSET=0
declare  -ix _slog_count=0
declare   -x _slog_file=''
declare   -x _slog_prefix=''
declare -xig __entities__=1
