#!/bin/bash
source entities || exit 2
	strict.set off

	if [[ -z "${hb_EXCLUDE[@]:-}" ]]; then
		declare -ax hb_EXCLUDE
		hb_EXCLUDE=( '~' '.gudang' 'gudang' '.old' '.bak' 'dev/' '.png' '.jpg' '.mp' '.iso' )
	fi

hashbang_main() {
	version.set '0.93'
	local dir='' search='' hashbang='bash' prefix='' suffix='' LF=$'\n' padfix=' '
	local -a gcmd=()
	local -i ccc=0 hbExclude=0 maxdepth=5
	while (( $# )); do
		if [[ "${1:0:1}" == '-' ]]; then
			case "$1" in
				-s|--search)		shift; search="${1:-}" ;;
				-m|--maxdepth)  shift; maxdepth=${1:-1} ;;
				-f|--padfix)		shift; padfix="${1:-}" ;;
				-p|--prefix)		shift; prefix="${1:-}${padfix}" ;;
				-x|--suffix)		shift; suffix="${padfix}${1:-}" ;;
				-X|--hb-exclude)
												hbExclude=1;;
				-Y|--no-hb-exclude)
												hbExclude=0;;
				-e|--exclude)		shift; hb_EXCLUDE+=( "$1" ); hbExclude=1;;
				-b|--hashbang)	shift; hashbang=${1:-bash};;
				-l|--nolf)			LF='' ;;
				-v|--verbose)		verbose.set on ;;
				-vv|-v2|--D|--debug)
												debug.set on ;;
				-q|--quiet)			verbose.set off; debug.set off;;
				-V|--version)		printTitle; return 0 ;;
				-h|--help)			usage; return 0	;;
				--)							shift
												gcmd+=( "$@" )
												break;;
				*)							gcmd+=( "$1" ) ;;
			esac
		else
			if (( ! ${#dir} )); then
				dir="$1"
			else
				gcmd+=( "$1" )
			fi				
		fi
		shift
	done
	
	[[ -z "${dir}" ]] 			&& dir='.'
	[[ -z "${gcmd[@]:-}" ]]	|| gcmd+=( '-l' )
	verbose									|| gcmd+=( '-s' )
	
	# report
#	(( ${#prefix} )) 		&& printf '%s\n' "$hashbang"
	msg "# $PRG $dir --hashbang '$hashbang'"
	(( ${#search} ))				&& msg " --search '$search'"
	(( ${#gcmd[@]} ))				&& msg " --grep ${gcmd[*]}"
	(( hbExclude ))					&& msg " --hb-exclude"
	[[ ${padfix} != ' ' ]]	&& msg " --padfix '${padfix}'"
	(( ${#prefix} ))				&& msg " --prefix '${prefix}'"
	(( ${#suffix} ))				&& msg " --suffix '${suffix}'"
	(( ! ${#LF} ))					&& msg " --nolf"
	msg '\n'
	
	if ((hbExclude)) && [[ -z ${hb_EXCLUDE[@]} ]]; then
		verbose && msg.warn "hb_EXCLUDE array envvar has not been set."
		hbExclude=0
	fi

	# execute
	files=( $(find ${dir} -maxdepth $maxdepth -type f) )
	local file='' e
	local -i incl=1
	for file in ${files[@]:-}; do
		# exclude files
		if ((hbExclude)); then
			for e in ${hb_EXCLUDE[@]}; do
				if [[ "$file" == *"${e}"* ]]; then
					debug && msg.warn "Excluded [$file] because of [$e]"
					incl=0
					break
				fi
			done 
			(( ! incl )) && { incl=1; continue; }
		fi
		# head/type examination
		ft=$(textfiletype -t "$file")
		[[ $ft == 'sh' ]] && ft='bash'
		if [[ $ft == "$hashbang" ]]; then
			if (( ${#search} )); then
				grep -I -m1 ${gcmd[@]:-} "$search" "$file" >/dev/null || file=''
			fi
			if [[ -n "${file}" ]]; then
				((++ccc))
				printf '%s%s%s %s' "${prefix}" "${file}" "${suffix}" "$LF"
			fi
		fi
	done
	(( ! ${#LF} )) && printf '\n'
	msg "# ${ccc} file$( ((ccc!=1)) && echo 's') found\n"
	return 0
}
cleanup() {
	local -i err=${1:-}
	exit $err
}

msg() {
	verbose && echo -en "${1:-}" 
	return 0
}
msg.warn() {
	echo >&2 -e "$PRG: $*"
}

printTitle() { echo "$(basename "$0") vs $(version.set)" ; return 0; }

usage() {
	local PRG
	PRG="$(basename "$0")"
	cat <<-ETX
	Script  : hashbang
	Version : $(version.set)
	Desc    : Search directory recursively for files with #!/bin/bash header.
	Synopsis: hashbang ["dir"]             Directory to start search ('.')
	        :   [-s|--search "str"]        String to find in found files.
	        :   [-b|--hashbang bash|php]   File type to search for ($hashbang)
	        :   [-X|--hb-exclude]          Exclude using hb_EXCLUDE array.
	        :   [-Y|--no-hb-exclude]       Do not use hb-exclude.
	        :   [-e|--exclude 'expr']      Add 'expr' to hb_EXCLUDE. Enables -X.
	        :   [-f|--padfix "str"]        Spacer for pre/suffix (' '). For no spacer: -f ''
	        :   [-p|--prefix "prefix"]     Prefix found files with "prefix".
	        :   [-x|--suffix "suffix"]     Suffix found files with "suffix".
	        :   [-l|--nolf]                Do not emit LF.
	        :   [-v|--verbose]             Verbose (default).
	        :   [-D|--debug]               Increase verbosity. Enables -v.
	        :   [-q|--quiet]               Just the facts, mam. Disables -v -D.
	        :   [--|--grep]                Pass all remaining parameters to grep.
	        : Note: All non-hashbang options are passed onto grep.
	 Example: # 0. print bash script filenames
	        : hashbang                   
	        : # 1. print bash filenames matching pattern
	        : hashbang . -s '^whereisit' 
	        : # 2. print bash filenames containing string 'varname'
	        : #    in format "p filename -s"
	        : hashbang . -s 'some_var_name' -p 'p' -x '-s' >editfiles
	ETX
}

hashbang_main "$@"
#fin
