#!/bin/bash
x="$(readlink -f "$0")"
PRGDIR=$(dirname $x)
PRG=$(basename "$x")
version.set() { echo '1.0'; }

declare -i verbose=1

main() {
	local dir='' search='' hashbang="#!$(which bash)" prefix='' suffix='' LF=$'\n'
	local -a gcmd=()
	local -i ccc=0
	while (($#)); do
		if [[ "${1:0:1}" == '-' ]]; then
			case "$1" in
				-h|--help)	
					usage
					;;
				-v|--verbose)	
					verbose=1
					;;
				-q|--quiet)	
					verbose=0
					;;
				-s|--search)
					shift
					search="${1:-}"
					;;
				-p|--prefix)
					shift
					prefix="${1:-} "
					;;
				-x|--suffix)
					shift
					suffix="${1:-}"
					;;
				-l|--nolf)
					LF=''
					;;
				-b|--hashbang)
					shift
					hashbang="$(which "${1:-junkfilex}")"
					if [[ -z "$hashbang" ]]; then
						hashbang="${1:-}"
						msg "# **Program [${1:-}] was not found. Using [${1:-}] as head search."
					else
						hashbang="#!${hashbang}"
					fi
					;;
				*)
					gcmd+=("$1")
					;;
			esac
		else
			if (( ! ${#dir} )); then
				dir="$1"
			else
				gcmd+=("$1")
			fi				
		fi
		shift
	done
	((${#dir}))		|| dir='.'
	((${#gcmd}))	|| gcmd+=("-l")
	((verbose))		|| gcmd+=("-s")

	# report
	((${#prefix})) && printf "$hashbang\n"
	msg "# $PRG $dir --hashbang '$hashbang'"
	((${#search}))  && msg " --search '$search'"
	((${#gcmd[@]})) && msg " --grep ${gcmd[*]}"
	((${#prefix})) 	&& msg " --prefix '${prefix}'"
	((${#suffix})) 	&& msg " --suffix '${suffix}'"
	((! ${#LF})) 		&& msg " --nolf"
	msg '\n'

	# execute
	files=( $(find "${dir}" -type f) )
	for f in ${files[@]}; do
		if [[ "$(head -n1 "$f" 2>/dev/null)" == "$hashbang" ]]; then
			((${#search})) && f="$(grep ${gcmd[@]} "$search" "$f")"
			((${#f})) && { ((ccc++)); printf '%s%s%s %s' "${prefix}" "${f}" "${suffix}" "$LF"; }
		fi
	done
	((! ${#LF})) && msg '\n'
	msg "# $ccc file$(((ccc!=1)) && echo s) found\n"
}


msg() {
	((verbose)) && echo -en "${1:-}" 
}

printTitle() { echo "$(basename $0) vs $(version.set)" ; }
usage() {
	local PRG=$(basename "$0")
	printTitle
	echo "Desc    : search directory recursively for files with \$!/bin/bash header."
	echo "Synopsis: $PRG dir [--search 'str'] [--hashbang bash|php|*]"
	echo "Examples: $PRG                    # print bash filename"
	echo "          $PRG . -s '^verbose'    # print matching bash file"
	echo "          $PRG . -s '^verbose' -H # print matching bash file with context"
	exit 1
}

main "$@"
#fin
